### ISSUE TITLE
SyntaxError: Unexpected token '('

### ISSUE THREAD

**Issue by andzejsp** [InnateAlpaca/pterosocket#3]
Hi i wanted to try out your module but i cant seem to get it up.

My index.js contains:
```js
const { pterosocket } = require('pterosocket')

const origin = "domain"; // your panel's domain
const api_key = "key"; //the api-key generated
const server_no = "num"; //the number of the server

const socket = new pterosocket(origin, api_key, server_no);

socket.on("start", ()=>{
    console.log("Connected!")
    socket.writeCommand("say console connected!");
})
```

and i cant run it. when i use `node index.js` i get this:
```fs
PS E:\js-ptero-console-output> node index.js
E:\js-ptero-console-output\node_modules\pterosocket\src\pterosocket.js:31
    async #authLogin(token = ""){
                    ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\VBA_PROJECTS\Git\andzejsp\js-ptero-console-output\node_modules\pterosocket\index.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
PS E:\js-ptero-console-output> 
```

What am i doing wrong?

**Comment by InnateAlpaca** [comment]
I'll look into it asap.

**Comment by InnateAlpaca** [comment]
Ok, so I tested it again (checking if they changed the api) and it works fine. Please give more details about your setup: how you installed the class, system you are using, and so on.

try running this command, and let me know the result
`node --version`
Last node version is 18.7.0. If you have a very old version that could explain the problems you are having.

**Comment by andzejsp** [comment]
Hi, i have the last node version v18.7.0.

**Comment by andzejsp** [comment]
Ok, i think it was my fault. When i tested last time i had the older version of node, then i updated to the new one but i didnt close the VSCODE terminal so i was on the old version and it gave me the same error. Now everything seems to work. :) Sorry for wasting your time.

**Comment by InnateAlpaca** [comment]
np :>
